### PR TITLE
Adding support for building an aarch64 image on dockerhub (x86)

### PR DESCRIPTION
**Pull request by KurtStam**
Patch for #287

Don't merge - if accepted it should stay on an aarch64 branch, unless we can parameterize the build using https://github.com/fabric8io-images/fish-pepper.

### CODE REVIEW

**Comment by kylemanna** [comment]
What is the intent of this pull request?  All the links are changed and the tests are broken.  Looks like your personal fork.

**Comment by KurtStam** [comment]
Closing this PR in favor of https://github.com/kylemanna/docker-openvpn/pull/292, which simply adds an Dockerfile.aarch64 file for an aarch64 container.

**Comment by lucaszanella** [comment]
Hi, I'm confused. Just tried, from docker hub, to run openvpn in my raspberry pi, and it didn't work. (gave an error about not being able to run in my arm architecture). What is going on? Shouldn't it be working by now?

**Comment by buchdag** [comment]
@lucaszanella this wasn't merged for the reasons exposed in #292 

You can however build a working version on your pi:

```
git clone https://github.com/kylemanna/docker-openvpn.git
cd docker-openvpn
docker build -t kylemanna/openvpn .
```

**Comment by mr-bolle** [comment]
A alternative way, to build the openvpn image from github directly

`docker build -t kylemanna/openvpn https://github.com/kylemanna/docker-openvpn.git`

**Pull request closed without merging**
