### PR TITLE
Push options need to be quoted

### PR DESCRIPTION
**Pull request by chepurko**
In OpenVPN 2.4 this is required, but it's also in the the man page; "Note that option must be enclosed in double quotes ("")." I couldn't get OpenVPN to start without adding the quotes, so this would make it future-proof but also bring it in to line with the official documentation.

### CODE REVIEW

**Comment by kylemanna** [comment]
This breaks the CI build, can you update, also can you provide a link mentioning quoting options?

Thanks!

**Comment by chepurko** [comment]
Sure, it's in the man pages https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage. Search on the page for "--push option". This is OpenVPN 2.4 but the requirement is there for [OpenVPN 2.3](https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage) as well.

> Note that option must be enclosed in double quotes ("").

Not sure why my build using OpenVPN 2.4 and `alpine:edge` failed to start and this build works. Basically I was getting this error on startup crash:

`Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/openvpn.conf:30: push (2.4.1)`

**Comment by kylemanna** [comment]
Thanks for the link.

I just created a code review request to implement your change in the `process_push_config` function so that all options are quoted as you describe instead of the two options in your original pull request.

We can merge this after:
1. Move the implementation to `process_push_config`, rebase to remove existing commit please.
2. Fix the Travis-CI tests that are failing because they don't expect the quotes

Thanks!

**Comment by chepurko** [comment]
Sorry, not sure how the test script works to figure out this build failure. [This line](https://travis-ci.org/kylemanna/docker-openvpn/jobs/230833739#L496) looks like there aren't any quotes around _route 172.22.22.0 255.255.255.0_, right?

**Comment by kylemanna** [comment]
The problem is that your update (which at first glance seems correct) breaks the rigid unit tests.  The test cases are now wrong.

The problem should be resolved by updating what the tests check for @ https://github.com/kylemanna/docker-openvpn/blob/909744dd7899870df764c2cc0a33ef01e9189849/test/tests/conf_options/container.sh#L48-L66

The tests need the double quotes added.

**Comment by chepurko** [comment]
Okay hopefully those `test.sh` changes are pretty enough. Travis CI checks passed. It looks like it's best to populate those `CONFIG_REQUIRED_*` variables with command substitution and `echo`.

**Comment by kylemanna** [comment]
Few comments:

1. Let's use single quotes as there are no variables it's much easier to read and less error prone, for example with the included `^` meta-character to be more explicit about matching:
        `CONFIG_REQUIRED_PUSH_ROUTE=$(echo "push \"route 172.22.22.0 255.255.255.0\"")`
        `CONFIG_REQUIRED_PUSH_ROUTE='^push "route 172.22.22.0 255.255.255.0"'`

2. Can you squash your branch down to two commits?  One for the test and one for the quotes?

With those two changes we can get this committed, thanks!

**Comment by chepurko** [comment]
@kylemanna But we'll have a literal `^` if it's inside the single quotes. Is the beginning-of-line character even necessary? What about:

`CONFIG_REQUIRED_PUSH_ROUTE='push "route 172.22.22.0 255.255.255.0"'`

**Comment by kylemanna** [comment]
> But we'll have a literal ^ if it's inside the single quotes. Is the beginning-of-line character even necessary? What about:

We want the literal `^` passed to `grep` so that it can use it make sure that the match begins at the beginning of the line and doesn't accidentally match something else.  Are you running into an issue with it?

Why would we want to make a unit test less explicit?

**Comment by chepurko** [comment]
Okay guess that did work.

Sorry, I'm a serial committer. I squashed the `container.sh` commits down but it all went horribly wrong when I tried to rebase something like `HEAD~2..HEAD~4` and I lost my work and started over. So I couldn't squash the `bin/ovpn_genconfig` commits. It's only 3...

**Comment by breznak** [comment]
> Sorry, I'm a serial committer. ...

There's github option for people like you and me which allows automatic squash on PR merge - it has its advantages and disadvantages, so the owner could decide this :)

**Comment by kylemanna** [comment]
> There's github option for people like you and me which allows automatic squash on PR merge - it has its advantages and disadvantages, so the owner could decide this :)

Unfortunately, there are 2 separate commits here (fixing the issue, and fixing the test), so a complete squash doesn't make sense.  I'll remove the revert commit and it's original commit and get this merged shortly.

Thanks all!

**Comment by kylemanna** [comment]
Merged manually in https://github.com/kylemanna/docker-openvpn/commit/78d612d181fdbb01ea0cdbae29df8f1c1df08e22

Thanks!

**Comment by kylemanna** [comment]
Merged manually @ https://github.com/kylemanna/docker-openvpn/commit/78d612d181fdbb01ea0cdbae29df8f1c1df08e22

Too bad there isn't a simple way to make github re-associate the updated branch with this pull request without pushing to @chepurko branch.

**Comment by chepurko** [comment]
Thanks.

**Pull request closed without merging**
