### PR TITLE
Add armhf support

### PR DESCRIPTION
**Pull request by ryansch**
I've got this running now on my raspberry pi 3 and it works beautifully.  The specs don't seem to be very happy though.

CI setup comes from https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/

### CODE REVIEW

**Comment by ryansch** [comment]
Note: I've published this at ryansch/openvpn:armhf-latest for testing.  Beware that it may suddenly disappear if this PR is merged.

**Comment by ryansch** [comment]
Here's how I set up my pi: https://gist.github.com/ryansch/e27604be323206a1e321e3b9bfb3b9f1

**Comment by kylemanna** [comment]
Is there an issue with the existing [Dockerfile.aarch64](https://github.com/kylemanna/docker-openvpn/blob/master/Dockerfile.aarch64)?  Why are add another one?  Am I missing something?

That said, I welcome the improvement to the Travis-CI build.

**Comment by ryansch** [comment]
Copied from #227:

@kylemanna Note that raspberry pi 2/3 are armhf/armv7 devices, not aarch64. I've got armhf support in #228.

**Comment by ryansch** [comment]
Apparently hypriot is trying to get an aarch64 build of linux running on the pi3: https://blog.hypriot.com/post/building-a-64bit-docker-os-for-rpi3/

That said, it won't help all of the existing installations that are using armhf.

**Comment by ryansch** [comment]
@kylemanna I've marked the armhf build as an allowed failure as I don't have time to figure out why the test suite is failing as the container works perfectly.

**Comment by ryansch** [comment]
@kylemanna Ping.

**Comment by kylemanna** [comment]
As I said here: https://github.com/kylemanna/docker-openvpn/pull/227#issuecomment-282416726

This doesn't make sense to me.  Especially since there isn't a way to test and verify the build even works without hardware.

**Comment by vielmetti** [comment]
It's possible to test a build on the Mac, which includes as of recently multiarch support in the form of QEMU that runs aarch64 (arm64) and also armhf (Raspberry Pi) containers.

**Comment by ryansch** [comment]
I'm planning to set up a mulitarch fork of this repo.

**Pull request closed without merging**
