### PR TITLE
Fix indents in "quick start"

### PR DESCRIPTION
**Pull request by menshikh-iv**
**Done:**
- no more spaces before an commands (important when you copy-paste it)
- ~add `export` for `OVPN_DATA`~

### CODE REVIEW

**Comment by kylemanna** [comment]
The clean-up of the spaces are welcome.  Docker Hub used to have a bug and hence why those were there, this has been resolved for some time though.

As for the `export`, why? The variable is only referenced from the commands running directly in the shell, none of the sub processes.

**Comment by menshikh-iv** [comment]
> As for the `export`, why? The variable is only referenced from the commands running directly in the shell, none of the sub processes.

You are right, change reverted.

Hope now PR can be merged.

**Comment by kylemanna** [comment]
Thanks.

**Comment by menshikh-iv** [comment]
@kylemanna thank you for this awesome project: it's fastest VPN setup ever that I did :bomb:

**Pull request merged**
