### PR TITLE
Two factor authentication using a token application

### PR DESCRIPTION
**Pull request by fabn**
This is a working implementation for #99 

It provides out of the box OTP authentication with token applications (e.g. Google Authenticator).

It's working and complete, the only issue I've encountered is that there's no google-authenticator prebuilt package for Alpine Linux so I reverted the image to be based on Debian Jessie.

Let me know what do you think and if you're willing to merge this I'll fix commands in otp documentation to point to your repository.

Meanwhile I configured a [hub image](https://hub.docker.com/r/fabn/openvpn/tags/) to experiment with this.

### CODE REVIEW

**Comment by fabn** [comment]
@kylemanna any feedback? 

I'd like to have this reviewed and possibly merged.

Also I tried to package and compile google_authenticator pam module for alpine linux but it seems impossible. It  always fails at [this line](https://github.com/google/google-authenticator/blob/195ddc135f8360254c459d037083ff46054df94f/libpam/pam_google_authenticator.c#L240).

I'll try to ask for help in GA repository but I don't know if it's something I can fix easily.

**Comment by kylemanna** [comment]
Hey @fabn, I haven't had a chance to review it.  Departing from Alpine Linux is a major negative though.


To merge a feature of this size I'd like to see some tests to confirm it works as I don't think I'll have a use for it and want to avoid bitrot.  Check out the basic tests and see if you can incorporate somethings to test it's functionality.

**Comment by fabn** [comment]
> Hey @fabn, I haven't had a chance to review it. Departing from Alpine Linux is a major negative though.

I was able to compile google-authenticator under Alpine Linux. Now I'm playing with with creation of a packaged version because it needs more than 350MB of dependencies to build and it's not something we'd want in a Docker image.

If you're interested you can follow my progress [here](https://github.com/fabn/alpine-sdk)

In any case having `debian:jessie` as base image is not so bad. Lot of images depends on that image and docker users may already have lot of shared layers. Maybe using ubuntu is even better from this point of view.

> To merge a feature of this size I'd like to see some tests to confirm it works as I don't think I'll have a use for it and want to avoid bitrot. Check out the basic tests and see if you can incorporate somethings to test it's functionality.

I'll see what I can do to test it in automated way, it might be difficult because OTP tokens are time based and they cannot be derived in a simple way. I can sketch something with HOTP that are counter based.

In any case my message was primary intended to know if you're interested in this work or not.

**Comment by fabn** [comment]
I've implemented a test for otp functionality. I've used an emergency code to avoid time based issues.

I tried my test in a virtual machine and it's working. Now I pushed a squashed commit to  trigger a new travis build since previous build is failed for a temporary network failure.

I also created (with some help) an [alpine linux package](http://bugs.alpinelinux.org/issues/5102) for google-authentication libraries. As soon as the x86_64 is present into alpine testing repository I'll try to move this setup to Alpine replacing Debian files.

**Comment by fabn** [comment]
I've found out that your current test suite is not executed as intended. If any of .sh files in tests folder exits with a non zero status its result is currently ignored. See for example [last master build](https://travis-ci.org/kylemanna/docker-openvpn/builds/99334063#L492).

**Comment by fabn** [comment]
Ok, my test is working now. However the whole test infrastructure is a bit fragile. May I suggest you to move to a real test framework instead of relying on bash files?

If you're interested I know two projects to test cli applications, one is [aruba](https://github.com/cucumber/aruba) and the other is [bats](https://github.com/sstephenson/bats). I used the latter for very small things it's pretty lightweight but kind of limited for real stuff. 

Aruba is a great project with a great ecosystem around it, however it has a steep learning curve especially if you don't know ruby/cucumber. Bonus feature you can publish your feature files as documentation [example](https://relishapp.com/rspec/rspec-core/v/3-4/docs/command-line/example-option)

If you're interested I can sketch a PR to start working with aruba, let me know.

**Comment by fabn** [comment]
Ok, now is working again with Alpine Linux. Let me know your final thoughts.

**Comment by 2devnull** [comment]
ok, cool. I have battling split-tunnel and reaching servers on private network. Once I get that all working, I attempt giving this a go.

**Comment by 2devnull** [comment]
Well, I am getting this error after entering the username and OTP. Also pamtester doesn't see to be available for alpinelinux so not sure how to debug.

`Fri Feb 12 13:14:17 2016 AUTH: Received control message: AUTH_FAILED
Fri Feb 12 13:14:17 2016 SIGTERM[soft,auth-failure] received, process exiting
`

**Comment by fabn** [comment]
@2devnull did you used image from hub or built it by yourself using my repo?

I spent sometime debugging this in Alpine Linux, the issue is that compiled package install pam module under `/usr/lib/security` thus pam subsystem won't find it

If I'm right you should find a line in your openvpn log saying 

    AUTH-PAM: BACKGROUND: user 'xxx' failed to authenticate: Module is unknown

This is also happening [in travis](https://travis-ci.org/kylemanna/docker-openvpn/builds/108589793#L777) however I missed that because the overall status was green.

I'll try to fix it in the next few days submitting a new alpine linux package and trying to check for it in automated tests.

Meanwhile you should able to solve it by doing this command in your vpn image:

```
docker exec -it <your-running-openvpn-image> bash
# In container:
mv /usr/lib/security/pam_google_authenticator.so /lib/security/
```

**Comment by 2devnull** [comment]
I pulled down the image from hub. I will try the workaround or just build it myself with that change.

Thanks.

**Comment by 2devnull** [comment]
I was able to try it after making the suggested change. It gave the same failure, but the I tried it with the username with the '@domain.com' part and then it succeeded. I believe I had tried that before and it didn't work so the pam_google_authenticator.so was most likely the required fix.

**Comment by fabn** [comment]
Username should be the same string you used in the `ovpn_otp_user` command.

In any case I submitted a fix for Pam module location to alpine Linux packages repo. I'll update this PR once it gets merged.

**Comment by fabn** [comment]
New packages were released today. This image will also include [pamtester](http://pamtester.sourceforge.net/) utility (only 32kb added to image) to debug pam authentication and configuration where needed.

**Comment by jlm** [comment]
I am interested in this project. Thanks for working on it.  So much easier than repeating the many steps required for a manual installation.

**Comment by kylemanna** [comment]
Sorry for not getting a chance to look at it.  Looks like you're back on Alpine Linux and have included tests that appear to pass.  Looks good to me.

**Pull request merged**
