### PR TITLE
gen Kubernetes secrets to hold config and credentials 

### PR DESCRIPTION
**Pull request by streamnsight**
This PR makes it easy to use this image in a Kubernetes cluster.
It helps generate the proper config to access services inside the Kubernetes cluster through the VPN, and generate a Secret.yaml file to hold the config and credentials, so that there is no need to have a volume or local mount to handle the PKI, certs and keys.

### CODE REVIEW

**Comment by kylemanna** [comment]
Interesting, not familiar wenough with Kurbernetes.  I'm hoping someone else can chime in and review / comment.

Also, can you move the documentation out of README.md and in to docs/kubernetes.md ?

**Comment by streamnsight** [comment]
I moved the docs.

Kubernetes orchestrates docker containers. 
VPN is very useful to access services inside the cluster without having to expose them outside.
The addition only checks if the KUBERNETES variable is set, and if so loads the config/certs/key from the Secret.
Secrets are the way to pass credentials to containers in a Kubernetes cluster so they are not mounted from disk or another container, and only accessible to those with permissions to control the cluster. 
If you use Docker extensively, you'll probably want to use Kubernetes at some point.
Cheers

**Comment by kylemanna** [comment]
Would it be possible to test this in an automated fashion like the basic [current tests](https://github.com/kylemanna/docker-openvpn/tree/master/tests)?  I'm concerned about bitrot and un-maintained code if it's not a popular use case.

**Comment by streamnsight** [comment]
@kylemanna 
I'll try to write a meaningful script but to functionally test you'd really need to spin this in a Kubernetes cluster.
There is really not much added here: a script to write a file that can be used as Secrets.
and the test on the KUBERNETES flag to load the Secrets in the right place.
No backward incompatibilities.

**Comment by meonkeys** [comment]
@streamnsight a local k8s cluster should just be a matter of starting a few docker containers, right? I'll try to make time to write a test if you're stuck (and if you'll help me when I get stuck). I want this too since I also run this openvpn container in a k8s cluster.

**Comment by streamnsight** [comment]
@meonkeys go for it... Kubernetes in docker, why not. just a lot of work for a test which doesn't bring much IMO. All this script does is save the relevant files into a secret.yaml config. Maybe we can just test that the files are in there. The rest is really Kubernetes related.

**Comment by onbjerg** [comment]
Some small cluster bootstrapping scripts for Kubernetes:

https://github.com/redspread/localkube
https://github.com/kubernetes/minikube

**Comment by onbjerg** [comment]
Can this be merged? I mean, what tests should there be? As @streamnsight said, it only puts the configuration in a YAML-file. The ``getsecrets`` script creates some directories.

If you want to, it is _possible_ (albeit probably not smart) to start a local k8s cluster and deploy the example YAML-files, but this would mean that we're pretty much testing against a specific k8s project to be working as well. Right?

**Comment by onbjerg** [comment]
By the way, on my cluster it didn't work with ``mv`` in ``getsecrets``, only ``cp``.

**Comment by onbjerg** [comment]
Also, a small note: I am using Google Container Engine, and kubedns has an IP of 10.0.4.10 instead of 10.0.3.10. I did not change the configs, so I assume this is the default for GKE. It would be a good addition to the docs.

**Comment by onbjerg** [comment]
Final note: updating on GCE might change the IP of kubedns.

**Comment by sstarcher** [comment]
@streamnsight following the instructions for this pull request I'm running into the same issue you ran into with https://github.com/skynetservices/skydns/issues/243

Any advice?

**Comment by sstarcher** [comment]
annnnnd the magic is that `cluster.local` conflicts with mdns.  You can either disable mdns or change the domain for the kubernetes dns to be something else.

**Comment by onbjerg** [comment]
@sstarcher We use this in production and it works fine. Some things do not work, for example you can't access ``app.production`` since all TLDs are reserved for future use. ``app.production.cluster.local`` works fine though.

What are you having troubles with?

**Comment by sstarcher** [comment]
@onbjerg cluster.local conflicts with mdns.  It works as long as you disable mdns or  change it to not end in .local

**Comment by pieterlange** [comment]
I'm doing something similar here: https://github.com/pieterlange/kube-openvpn

This repo has been a huge inspiration. Thanks @kylemanna !

**Comment by ensonic** [comment]
After spedning one day, I found this PR. Would be great to merge it. Now manually replicating some parts.

**Comment by kylemanna** [comment]
> After spedning one day, I found this PR. Would be great to merge it. Now manually replicating some parts.

To be merged, it needs tests to ensure things don't break.

**Comment by cemo** [comment]
@streamnsight would you add necessary parts? This is huge amount work and it is really nice. I will use as well. Thanks for your efforts.

**Comment by cemo** [comment]
I think that `getsecret` file and related changes can be easily tackled. I have changed the necessary k8s descriptor. Here is the sample:

https://gist.github.com/cemo/5dce9fdca778330be0dd69d9a71d2589 

This does not require `getsecrets` file.

**Comment by kylemanna** [comment]
Hey guys,

Had a chance to play with Kubernetes for a project the other day and now have at least a clue at what's going on.  How many people are using this?

I'd like to explore merging this, but have a few tweaks I'd like to see as as well as know if someone will be around to field k8s questions as they arise.

**Comment by pieterlange** [comment]
I'm not using this but my own fork, but happy to help if you have questions.

The biggest issue for me is dealing with the PKI system as i don't want a stateful container. I'm thinking about turning my fork into an operator to solve a bunch of problems at once, but that will take some time. And is probably out of scope for a generic docker-openvpn image.

**Comment by streamnsight** [comment]
This was made to avoid having the PKI in the container, just create creds and then build a Secret to pass them to an instance as it needs it.
This is kinda old now. I used DaemonSets originally to pin the container to a given host node, otherwise it's difficult to give it outside access without a load balancer in the mix.

@kylemanna what kind of 'tweaks' are you thinking about?

**Comment by MatthewVance** [comment]
This looks interesting. Given the security nature of OpenVPN, would it be possible to better manage Secrets? Kubernetes secret object type is secure as one would think it should be given its intent to hold sensitive passwords, keys, etc. The [official docs](https://kubernetes.io/docs/concepts/configuration/secret/#risks) outline a number of security risks to bear in mind. Given all those risks, it'd be better to implement a more secure alternative.

The *[Secrets and LIE-abilities: The State of Modern Secret Management (2017)](https://medium.com/on-docker/secrets-and-lie-abilities-the-state-of-modern-secret-management-2017-c82ec9136a3d)* article outlines pros/cons of various secret management options. For this use case, I lean towards [Vault by HashiCorp](https://github.com/hashicorp/vault).

**Comment by pieterlange** [comment]
I think it's reasonably OK, as long as you dont store the CA private key in the cluster.

**Comment by streamnsight** [comment]
@pieterlange @MatthewVance 
That's what my original PR was meant to do: generate CA / keys locally, and create secrets for the user keys, that can then be attached to the VPN container, but PKI stays local / private.
I haven't followed on the forks in a while 
I see @pieterlange has one as well as https://github.com/redspread/kube-openvpn
Not sure which is recommended these days...

**Pull request closed without merging**
