### PR TITLE
Add port sharing example to tcp doc

### PR DESCRIPTION
**Pull request by buchdag**
Works like a charm with [nginx-proxy](https://github.com/jwilder/nginx-proxy).

### CODE REVIEW

**Comment by buchdag** [comment]
Also, that answers #316

**Comment by kylemanna** [comment]
This is a cool feature, was unaware of `port-share`.  Thanks for writing it up.

**Comment by flexbrane** [comment]
@buchdag, can you provide your configuration (or an exemple) in order to use nginx proxy and port share?

I tried [according to the exemple](https://github.com/kylemanna/docker-openvpn/blob/master/docs/tcp.md), but without success.

**Comment by buchdag** [comment]
Shure. The way I do it is:

1) create a docker network for nginx-proxy

```
docker network create --subnet 172.18.0.0/16 -o "com.docker.network.bridge.name"="nginx-proxy"
```

The subnet you'll use is up to you and the bridge name is there just to have a cleaner interface name.

2) launch nginx-proxy with the 443 port published to something else (here 4545)

```
docker run -d \
  --name nginx-proxy \
  -p 80:80 \
  -p 4545:443 \
  --network nginx-proxy \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  jwilder/nginx-proxy
```

3) create your openvpn volume:

```
OVPN_DATA=openvpn
docker volume create $OVPN_DATA
```

4) run `ovpn_config` with the port-share option pointing to the docker network gateway:

```
docker run --rm \
  -v $OVPN_DATA:/etc/openvpn \
  kylemanna/openvpn ovpn_genconfig \
  -u tcp://vpn.yourdomain.tld:443 \
  -e 'port-share 172.18.0.1 4545'
```

5) init the pki and create your client:

```
docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki
docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full foo
```

6) run the openvpn container with the correct port publishing:

```
docker run -d \
  --name openvpn-server \
  -p 443:1194/tcp \
  --cap-add=NET_ADMIN \
  -v $OVPN_DATA:/etc/openvpn \
  kylemanna/openvpn
```

**Pull request merged**
