### PR TITLE
Secure ca script

### PR DESCRIPTION
**Pull request by ivlis**
I wrote a script that allows one to separate a CA root key. 

Also, I believe, that it should be a default recommended way to setup the PKI.

### CODE REVIEW

**Comment by ivlis** [comment]
Not interested?

**Comment by ypid** [comment]
I don’t quite get it what the advantage of your DVC approach is over the simple bind mounting and storing the files directly on a host. Can you explain that? I think it just adds complexity for this use case.

I agree that it should be the default recommended way.

**Comment by kylemanna** [comment]
I agree with @ypid here.  There are many complex solutions possible with OpenVPN and those elaborate solutions should look at using a host bind mount.

The goal of this repository is to take the most common use case and make it extremely easy to use.

**Comment by ivlis** [comment]
DVCs are the recommended way to manage data in Docker, it does not pollute the host file system, it is compatible with a private Docker registry and is it more secure, as only root (or a member of the docker group) can access the container. One can easily change hosts by pushing/pulling containers via a Docker registry. If data are stored in a host's directory one must tar and copy it manually, what ruins the idea of containers.

I agree with @kylemanna, the goal should be to keep things as simple as possible. It the repo does its job!  However,  security and flexibility should not suffer. Probably, a collection of scripts can be created, where one can init a PKI, create a server and so on by running a single script. After that. it is irrelevant how complex are the scripts, if a user just run them to get a result.

**Comment by ypid** [comment]
@ivlis Right. I understand the advantages of DVC but I am not quite sure that DVC is the best thing for this particular use case. I for example keep the root CA key and so on in an encfs container on my workstation. Those kinds of things are not easily accomplished with DVC. Also, I don’t think that the aspect of pushing the PKI DVC to even a private registry is a good idea. I would say the best is to keep this on one machine only. Maybe you can extend the paranoid docs to mention both ways (bind mount/DVC) if you still think that the DVC approach adds something in your setup.

**Comment by ivlis** [comment]
@ypid Sure, I'll do that. You are correct, probably CA root keys should sit alone in a secure place, but it is not true for server keys, as one may have a number of servers for the same CA on one machine (for tcp and udp, for example) or on different machines for load balancing.

**Pull request closed without merging**
