### PR TITLE
Updated documentation.

### PR DESCRIPTION
**Pull request by ypid**
* Related to https://github.com/kylemanna/docker-openvpn/pull/54
* ~~Allow better syntax highlighting.~~
* Added/Fixed hyperlinks.
* Spelling.

### CODE REVIEW

**Comment by kylemanna** [comment]
A lot of typos on my part.  Oops!  Thanks for finding and reading.

What's the benefit of the the shell syntax? Appears to be rendered the same and is alot harder to read in plain-text mode as I most often do.

**Comment by ypid** [comment]
Currently probably not much benefit. But I know other formats which look quite nice with syntax highlighting (for variables and so on) https://github.com/nickjj/ansigenome/pull/26. For now it just makes it explicit that something is a shell command.

**Comment by kylemanna** [comment]
I'd love to merge the typo fixes.

The shell mark-up looks like alot of noise for no visible value.  I'm also concerned that the shell markdown appears to be a [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) feature.  I'm not sure if it would work well on https://hub.docker.com

Can you split the commit in your branch so we can move the typos forward? :+1: 

It's easier to merge things when the commits are broken up in to smaller atomic commits such as `docs: Fix miscellaneous typos and clarifications` and `docs: Convert to shell Github flavored markdown`.    The [Linux kernel has a great guide](https://www.kernel.org/doc/Documentation/SubmittingPatches) on this topic, but is extremely verbose.  I typically default to following those guidelines.

**Comment by ypid** [comment]
I just tested the Github flavored markdown on https://hub.docker.com and it works like the 4-space-indention (also without highlighting currently).

Sorry about not spiting the PR. I will just revert the Github flavored markdown thing.

**Comment by ypid** [comment]
This is how the Github flavored markdown would look like:

https://github.com/jchaney/owncloud
https://hub.docker.com/r/jchaney/owncloud/

I guess I am also not fully convinced about syntax highlighting for Shell.

**Pull request merged**
