### PR TITLE
allow specifying extra config

### PR DESCRIPTION
**Pull request by justone**
Quick change to allow adding arbitrary config bits to the openvpn.conf file.

### CODE REVIEW

**Comment by ypid** [comment]
:+1: Somewhat related to #67 in which I did the same thing for client options (not merged).

**Comment by kylemanna** [comment]
Can you add a unit test that tests that multiple arguments are passed and then end up in the generated config file as expected?

**Comment by justone** [comment]
@kylemanna 

Sure thing.  Tests added.

**Comment by kylemanna** [comment]
Thanks!

**Comment by justone** [comment]
Awesome, thanks!

**Pull request merged**
