### PR TITLE
add openldap-clients to image

### PR DESCRIPTION
**Pull request by flypenguin**
We use a script to verify against LDAP, and the script needs `ldapsearch` installed. If that would be present we could use the container as it is, which would be fabulous ;)

The full-blown ldap support would be nice as well, on the other hand that is a low-key solution that works for now.

### CODE REVIEW

**Comment by marvin-w** [comment]
From my point of view it would make more sense to extend from this image and install the required libraries yourself.

I understand your usecase, but everyone has different use cases and extending from it is as simple as:

```
FROM kylemanna/openvpn

RUN apk add --update openldap-clients && \
     rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*
```

Then, optionally, tag it and push it to your repository, assuming you have one.

You could also use docker-compose to do that for you.

**Comment by rvalle** [comment]
hi! just found this thread searching for openvpn with ldap.

I don't agree 100% with @marvin-w , while extending the image is certainly easy, maintaining it over time is a task, a duplicated task.

I think having core-pluings included, activated only if pertinent environment variables are used, its a good compromise.

If core plugin growth becomes a problem we could have a -slim version of the image as seems standard practice in docker, thou in this case, I don't think there are many plugins to include.

Both images should be delivered with the same CD/CI process.

**Comment by flypenguin** [comment]
so? :D

**Comment by marvin-w** [comment]
Can you share the script that you are using for your LDAP integration? I might need that as well.

I'm not the owner of this repository so this isn't a decision that I can elaborate on.

Feel free to open a PR and try if it gets merged ;).

**Comment by flypenguin** [comment]
oh ... I no longer have it. it was just a basic ldaps search command with a bind dn user. or so I remember ... I just found the PR and saw it was still open ;)

**Comment by marvin-w** [comment]
Oh this is the PR, wow it looks all the same on the phone.

I don't think this repository is really maintained right?

**Comment by flypenguin** [comment]
no idea at all :D . like I said - I just punched the comment in ...
but apparently there's at lease one person watching the PRs, so it's not
totally dead ;)

Am Do., 15. Aug. 2019 um 18:09 Uhr schrieb Marvin Wichmann <
notifications@github.com>:

**Comment by flypenguin** [comment]
but ... solved? 😄

**Comment by kylemanna** [comment]
No, I'm not going to add features to this image I don't personally use or don't come with a battery of tests. Sorry, but this is a recipe for breakage and surprises to people depending on this container.

Others are welcome to fork and add it.

**Comment by rvalle** [comment]
that makes sense... or asking the contributor to provide a test.

**Comment by kylemanna** [comment]
> that makes sense... or asking the contributor to provide a test.

Yes, It's a hard line. But I started this docker image years ago for myself and it has grown in usage and use cases beyond my wildest imagination.  Supporting all these use cases was never my intent and often results in disappointment for the users when they are break.

**Pull request closed without merging**
