### PR TITLE
Support for RPI

### PR DESCRIPTION
**Pull request by x11tete11x**
Hi!, i had started a fork of your project to port your excelent work to a Raspberry Pi, BTW then i realize that it have no sense keep this on a own repo cause the difference it's almost nothing, so i propose make another brach with this little change (if you just use Alpine ARM works perfectly good all that you do) 

Tested and running on a RPI II with Hypriot OS (https://blog.hypriot.com/)

First time that i made Pull request im not sure if this is the correct way to do this (cause looks like it's a pull to your master branch)

### CODE REVIEW

**Comment by kylemanna** [comment]
#226 already does this

**Comment by ryansch** [comment]
@kylemanna Note that raspberry pi 2/3 are armhf/armv7 devices, not aarch64.  I've got armhf support in #228.

**Comment by x11tete11x** [comment]
Thx!, little question im getting start with this, then i don't understand some thing what travis.yml does?, i mean if i do docker pull kylemanna/openvpn that file recognize that it should use Dockerfile.armhf if im on arm?, thx!

**Comment by ryansch** [comment]
@x11tete11x You've got two questions there.

1. travis.yml is for running specs on travis-ci.  Here's the last build for my PR: https://travis-ci.org/kylemanna/docker-openvpn/builds/205054280

2. Docker doesn't (yet) have support for multiple architectures. @kylemanna would need to build from these arch specific Dockerfiles and push them to alternate tags (like armhf-latest, aarch64-latest).  See https://github.com/multiarch/alpine for an example of a project building for multiple repos.

**Comment by x11tete11x** [comment]
Thx for clarify! :D

**Comment by kylemanna** [comment]
> Docker doesn't (yet) have support for multiple architectures. @kylemanna would need to build from these arch specific Dockerfiles and push them to alternate tags (like armhf-latest, aarch64-latest). See https://github.com/multiarch/alpine for an example of a project building for multiple architectures.

Yes.  I looked at this, and started this, but I'd have to build them manually.  Docker Hub won't built them automatically after initial review.  If anyone knows how to get Docker Hub to built alternative archs automatically I'm all ears to implement it.

As for running this on 32-bit ARM platforms, I'll probably never add that support.  Performance is horrific on 64-bit ARM platforms, and supporting older rPis is kind of frivolous.  Use the native client/server on these platforms.  This docker image is intended to server as a server, which is a tall order for a resource constrained pi3 even.

**Comment by ryansch** [comment]
@kylemanna I'm connected to my pi3 from a coffee shop and performance is great!

I'd recommend using travis-ci to build the images as per https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/

If you choose not to support multiple architectures please let me know as I'd love to host that.

**Comment by kylemanna** [comment]
> @kylemanna I'm connected to my pi3 from a coffee shop and performance is great!

Your rpi3 is 64-bits, which I don't have issue with, it's the older platforms that seem frivolous.

**Comment by ryansch** [comment]
@kylemanna Actually because the pi3 runs a 32 bit kernel built for armv7.  To my knowledge, nobody has gotten 64-bit armv8 working on the device yet.  Both the pi2 and pi3 run the same kernel so we have to play the armhf game.

**Comment by vielmetti** [comment]
Performance suffers on 64-bit ARM because the needful crypto bits have not yet all been implemented in arm64 assembler. However if you have enough 64-bit cores you get very acceptable per-core performance (e.g. on the 96-core Cavium based Packet 2A server which I was routinely routing my own traffic through in test mode). I don't have complete benchmark data yet on performance so it's clearly pre-production.

**Pull request closed without merging**
